楽しい:
  - 嬉しい
  - うれしい
  - 楽しみ
  - 楽しかった
  - happy
悲しい:
  - 悲しみ
  - かなしい
  - 萎え
  - 萎えた
怒り:
  - ムカつく
  - むかつく
  - イライラ
不安:
  - こわい
  - 怖い
  - 心配
しんどい:
  - 疲れた
  - だるい
  - 眠い
中立:
  - 普通
  - ふつう
  - ok
  - OK
  - ニュートラル
  - 特になし
